# Site Settings
title: ResumeDPC
url: 'http://dpalomaresc.github.io'
baseurl: '/resumedpc' #change it according to your repository name
# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Diego Palomares
tagline: iOS Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I'm Information Technologies Engenieer with 4 years of experience as iOS developer.
skilled at write code, design and maintain iOS aplications with language swift and Objective-C.
strong comunication, interpersonal  and teamwork skills"

#sidebar links
email: diego.palomares8@gmail.com
phone: 4611820081
#website: blog.webjeda.com #do not add http://
linkedin: diego-palomares-8a7b19124
#github: diegoluke
twitter: '@diegoluke1'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
